name: reados

include:
  - ./config/compose/traefik.compose.yaml
  - ./config/compose/pgadmin.compose.yaml
  - ./config/compose/frontend.compose.yaml
  - ./config/compose/core.compose.yaml
  - ./config/compose/tenant.compose.yaml
  - ./config/compose/authentication.compose.yaml
  - ./config/compose/accounting.compose.yaml
  - ./config/compose/postgres.compose.yaml

networks:
  reados:
    driver: bridge

volumes:
  pgadmin_data:
  frontend_node_modules:
  core_node_modules:
  tenant_node_modules:
  authentication_node_modules:
  accounting_node_modules:
  postgres_data:
