services:
  seed:
    build:
      context: .
      dockerfile: ./config/compose/server.dockerfile
    env_file:
      - ./seed.env
    entrypoint: ["npm", "run", "seed", "--"]
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - seed_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - reados

volumes:
  seed_node_modules:
